### ISSUE TITLE
No support for Statamic 4

### ISSUE THREAD

**Issue by benfreke** [jedamzik/statamic-toc#7]
Hi

I just tried to upgrade to v4 of Statamic and this plugin doesn't support it. 

It is less than a month since it was out, but I was wondering if there are plans to keep this plugin updated and supporting Statamic 4? Are you accepting pull requests?

**Comment by jedamzik** [comment]
Hi Ben,

`v1.3.1` now also supports Statamic v4.

1fd74beff488de6b9f09697a16d460f2ca5e2d50
